# Generated by Django 6.0.1 on 2026-01-22 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_coop_id_customuser_house_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='house_number',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Номер будинку'),
        ),
    ]
