# Generated by Django 6.0 on 2026-01-06 15:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cooperative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Назва кооперативу')),
                ('inn', models.CharField(blank=True, max_length=20, verbose_name='ЄДРПОУ')),
            ],
            options={
                'verbose_name': 'Кооператив',
                'verbose_name_plural': 'Кооперативи',
            },
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('member', 'Учасник'), ('chairman', 'Голова правління'), ('vice_chairman', 'Зам голови'), ('accountant', 'Бухгалтер')], default='member', max_length=20, verbose_name='Роль')),
                ('plot_number', models.CharField(max_length=20, verbose_name='Номер ділянки/квартири')),
                ('date_joined', models.DateField(auto_now_add=True, verbose_name='Дата вступу')),
                ('cooperative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cooperatives.cooperative', verbose_name='Кооператив')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Користувач')),
            ],
            options={
                'verbose_name': 'Член кооперативу',
                'verbose_name_plural': 'Члени кооперативів',
            },
        ),
    ]
