# Generated by Django 6.0 on 2026-01-08 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooperatives', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CooperativeApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Назва кооперативу')),
                ('address', models.CharField(max_length=255, verbose_name='Адреса будинку')),
                ('contact_name', models.CharField(max_length=100, verbose_name='ПІБ Голови/Контактної особи')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('email', models.EmailField(max_length=254, verbose_name="Email для зв'язку")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('new', 'Нова заявка'), ('approved', 'Схвалено'), ('rejected', 'Відхилено')], default='new', max_length=10)),
            ],
            options={
                'verbose_name': 'Заявка на кооператив',
                'verbose_name_plural': 'Заявки на кооперативи',
            },
        ),
    ]
