# Generated by Django 6.0.1 on 2026-01-22 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooperatives', '0003_cooperativeapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='cooperative',
            name='price_day',
            field=models.DecimalField(decimal_places=2, default=2.64, max_digits=10, verbose_name='Тариф День (грн/кВт)'),
        ),
        migrations.AddField(
            model_name='cooperative',
            name='price_night',
            field=models.DecimalField(decimal_places=2, default=1.32, max_digits=10, verbose_name='Тариф Ніч (грн/кВт)'),
        ),
    ]
