# Generated by Django 6.0 on 2026-01-07 09:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cooperatives', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('el', 'Електроенергія')], default='el', max_length=10, verbose_name='Тип')),
                ('hierarchy', models.CharField(choices=[('individual', 'Особистий (Будинок/Квартира)'), ('street', 'Вуличний (Баланс вулиці)'), ('global', 'Головний (Баланс кооперативу)')], default='individual', max_length=20, verbose_name='Рівень')),
                ('number', models.CharField(max_length=50, verbose_name='Серійний номер')),
                ('is_two_zone', models.BooleanField(default=False, verbose_name='Двозонний (День/Ніч)')),
                ('initial_value', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Початковий показник')),
                ('cooperative', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cooperatives.cooperative', verbose_name='Кооператив')),
                ('membership', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cooperatives.membership', verbose_name='Власник')),
                ('street', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cooperatives.street', verbose_name='Вулиця')),
            ],
            options={
                'verbose_name': 'Лічильник',
                'verbose_name_plural': 'Лічильники',
            },
        ),
        migrations.CreateModel(
            name='Reading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_total', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Загальний (Т)')),
                ('value_day', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='День (Т1)')),
                ('value_night', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Ніч (Т2)')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Дата подачі')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='readings/', verbose_name='Фото')),
                ('meter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='meters.meter', verbose_name='Лічильник')),
            ],
            options={
                'verbose_name': 'Показник',
                'verbose_name_plural': 'Показники (Історія)',
                'ordering': ['-date'],
            },
        ),
    ]
