# Generated by Django 6.0.1 on 2026-01-22 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meters', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meter',
            name='number',
            field=models.CharField(max_length=50, unique=True, verbose_name='Серійний номер'),
        ),
    ]
